/* 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

class Problem44 {
  public static boolean isPentagonal(int i) {
    int n = (int) Math.sqrt(2*((double)i)/3);
    int pentagonal = pentagonal(n);;
    while(pentagonal < i) {
      n++;
      pentagonal = pentagonal(n);
    }
    return pentagonal == i;
  }
  
  public static int pentagonal(int n) {
    return n*(3*n-1)/2;
  }
  
  public static void main(String argv[]) {
    int difference = -1;
    for(int i = 2; difference == -1 && i > 0 && i < 10000; ++i) {
      for(int j = i - 1; difference == -1 && j >0; --j) {
        int sum = pentagonal(i) + pentagonal(j);
        int diff = pentagonal(i) - pentagonal(j);
        if(isPentagonal(sum) && isPentagonal(diff)) {
          System.out.println(i + " is " + pentagonal(i) +
              "\n" + j + " is " + pentagonal(j) +
              "\nsum = " + sum + " diff= " + diff);
          difference = diff;  
        }
      }
    }
    if(difference > 0)
      System.out.println(difference);
    else
      System.out.println("overflow");
  }
}
